HighRoller:
  id: 1
  name: High Roller
  description: I have spent a lot of money on this site.
  levels:
    - 10
    - 100
    - 500

Busy:
  id: 2
  name: Busy
  description: I have put a lot of projects on here.
  levels:
    - 1
    - 2
    - 3

Acceptable:
  id: 3
  name: Acceptable
  description: People generally like my work.
  levels:
    - 0.9

Completionist:
  id: 4
  name: Completionist
  description: I get stuff done.
  levels:
    - 1
    - 10
    - 20

Helpful:
  id: 5
  name: Helpful
  description: I have supported a lot of issues.
  levels:
    - 1
    - 5
    - 10

Likable:
  id: 6
  name: Likable
  description: A lot of people support my work.
  levels:
    - 1
    - 5
    - 10

OldTimer:
  id: 7
  name: Old Timer
  description: I have been here a while.
  levels:
    - 1
    - 5
    - 10
